# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('direct_red', 'Direct Red'), ('red', 'Red'), ('yellow', 'Yellow')], default='red', max_length=50)),
                ('minute', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('championships', models.IntegerField(default=0)),
                ('runnerups', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CoachTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('championships', models.IntegerField(default=0)),
                ('runnerups', models.IntegerField(default=0)),
                ('games', models.IntegerField(default=0)),
                ('games_as_started', models.IntegerField(default=0)),
                ('games_as_substituted', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Coach')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('number', models.IntegerField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('income', models.IntegerField(blank=True, null=True)),
                ('audience', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter', models.BooleanField(default=True)),
                ('minutes', models.FloatField(blank=True, null=True)),
                ('goals', models.IntegerField(default=0)),
                ('cards', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Game')),
            ],
        ),
        migrations.CreateModel(
            name='GameReferee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main', 'Main'), ('lineman', 'Lineman'), ('fourth', 'Fourth'), ('other', 'Other')], default='main', max_length=50)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Game')),
            ],
        ),
        migrations.CreateModel(
            name='GameTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.BooleanField(default=True)),
                ('goals', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('penalty', 'Penalty'), ('freekick', 'Freekick'), ('head', 'Head'), ('right', 'Right'), ('left', 'Left')], max_length=50, null=True)),
                ('minute', models.IntegerField(blank=True, null=True)),
                ('own', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('picture', models.ImageField(null=True, upload_to=b'')),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('positions', models.CharField(blank=True, choices=[('goalkeeper', 'Goalkeeper'), ('defense', 'Defense'), ('midfielder', 'Midfielder'), ('forward', 'Forward')], max_length=50, null=True)),
                ('leg', models.CharField(blank=True, choices=[('right', 'Right'), ('left', 'Left'), ('both', 'Both')], max_length=50, null=True)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Country')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_joined', models.DateField()),
                ('transfer_us_dollar', models.FloatField(blank=True, null=True)),
                ('championships', models.IntegerField(default=0)),
                ('runnerups', models.IntegerField(default=0)),
                ('games', models.IntegerField(default=0)),
                ('games_as_started', models.IntegerField(default=0)),
                ('games_as_substituted', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('cards', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('queried', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('owner_type', models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.City')),
            ],
        ),
        migrations.CreateModel(
            name='StadiumTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True)),
                ('source', models.ManyToManyField(to='defense.Source')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Stadium')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('badge', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('championships', models.IntegerField(default=0)),
                ('runnerups', models.IntegerField(default=0)),
                ('total_games', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('goals_conceded', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.City')),
                ('coaches', models.ManyToManyField(through='defense.CoachTeam', to='defense.Coach')),
                ('players', models.ManyToManyField(through='defense.PlayerTeam', to='defense.Player')),
                ('stadium', models.ManyToManyField(through='defense.StadiumTeam', to='defense.Stadium')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('league', models.CharField(blank=True, choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('fourth', 'Fourth')], max_length=50, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('edition', models.IntegerField(blank=True, null=True)),
                ('points_for_victory', models.IntegerField(default=3)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Country')),
                ('source', models.ManyToManyField(to='defense.Source')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('goals_conceded', models.IntegerField(default=0)),
                ('cards', models.IntegerField(default=0)),
                ('final_position', models.IntegerField(default=0)),
                ('final_status', models.CharField(choices=[('champion', 'Champion'), ('runnerup', 'Runnerup'), ('int_cup', 'International Cup'), ('relegation', 'Relegation'), ('subrelegation', 'Sub Relegation'), ('other', 'Other')], default='other', max_length=50)),
                ('source', models.ManyToManyField(to='defense.Source')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Tournament')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(through='defense.TournamentTeam', to='defense.Team'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='top_scorers',
            field=models.ManyToManyField(to='defense.Player'),
        ),
        migrations.AddField(
            model_name='stadiumteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Team'),
        ),
        migrations.AddField(
            model_name='playerteam',
            name='source',
            field=models.ManyToManyField(to='defense.Source'),
        ),
        migrations.AddField(
            model_name='playerteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Team'),
        ),
        migrations.AddField(
            model_name='goal',
            name='assistant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistances', to='defense.Player'),
        ),
        migrations.AddField(
            model_name='goal',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='defense.Player'),
        ),
        migrations.AddField(
            model_name='goal',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Game'),
        ),
        migrations.AddField(
            model_name='goal',
            name='source',
            field=models.ManyToManyField(to='defense.Source'),
        ),
        migrations.AddField(
            model_name='gameteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Team'),
        ),
        migrations.AddField(
            model_name='gamereferee',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Referee'),
        ),
        migrations.AddField(
            model_name='gamereferee',
            name='source',
            field=models.ManyToManyField(to='defense.Source'),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Player'),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='source',
            field=models.ManyToManyField(to='defense.Source'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(through='defense.GamePlayer', to='defense.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='referees',
            field=models.ManyToManyField(through='defense.GameReferee', to='defense.Referee'),
        ),
        migrations.AddField(
            model_name='game',
            name='source',
            field=models.ManyToManyField(to='defense.Source'),
        ),
        migrations.AddField(
            model_name='game',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Stadium'),
        ),
        migrations.AddField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(through='defense.GameTeam', to='defense.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Tournament'),
        ),
        migrations.AddField(
            model_name='coachteam',
            name='source',
            field=models.ManyToManyField(to='defense.Source'),
        ),
        migrations.AddField(
            model_name='coachteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Team'),
        ),
        migrations.AddField(
            model_name='coach',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Region'),
        ),
        migrations.AddField(
            model_name='card',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Player'),
        ),
        migrations.AddField(
            model_name='card',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Game'),
        ),
        migrations.AddField(
            model_name='card',
            name='source',
            field=models.ManyToManyField(to='defense.Source'),
        ),
    ]
