# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachteam',
            name='games_as_started',
        ),
        migrations.RemoveField(
            model_name='coachteam',
            name='games_as_substituted',
        ),
        migrations.AddField(
            model_name='coachteam',
            name='transfer_us_dollar',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
