# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0002_auto_20170611_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameteam',
            name='tactic',
            field=models.CharField(choices=[('442', '4-4-2'), ('433', '4-3-3'), ('352', '4-5-2'), ('532', '5-3-2'), ('523', '5-2-3'), ('343', '3-4-3'), ('532', '5-3-2'), ('2143', '2-1-4-3'), ('3142', '3-1-4-2'), ('3223', '3-2-2-3'), ('3232', '3-2-3-2'), ('4411', '4-4-1-1'), ('4141', '4-1-4-1'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
