# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0003_gameteam_tactic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(default=0)),
                ('cards', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(default=0)),
                ('as_starter', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Player')),
                ('source', models.ManyToManyField(to='defense.Source')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Tournament')),
            ],
        ),
    ]
