# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0006_auto_20170616_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='wikipedia_page',
            field=models.URLField(blank=True, null=True),
        ),
    ]
