# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0007_team_wikipedia_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
