# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0011_auto_20170616_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='wikipedia_page',
            new_name='source',
        ),
    ]
