# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0012_auto_20170617_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonTeamFinalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('games', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('goals_conceded', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentReferee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.IntegerField(default=0)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Referee')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='tournamentteam',
            name='final_status',
        ),
        migrations.AddField(
            model_name='tournament',
            name='champion_of_season',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='type',
            field=models.CharField(choices=[('penalty', 'Penalty'), ('freekick', 'Freekick'), ('head', 'Head'), ('right', 'Right'), ('left', 'Left'), ('owngoal', 'Own Goal')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentreferee',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Tournament'),
        ),
        migrations.AddField(
            model_name='seasonteamfinalstatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.TournamentStatus'),
        ),
        migrations.AddField(
            model_name='seasonteamfinalstatus',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.Team'),
        ),
    ]
