# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-09 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0013_auto_20170908_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='additional_info',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='end_string',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='number_of_teams',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='tournament',
            name='record_problem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='result_source',
            field=models.ManyToManyField(related_name='results_source', to='defense.Source'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rounds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='season_champion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_string',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='system',
            field=models.CharField(blank=True, choices=[('todos', 'Todos contra todos'), ('liguilla', 'Liguilla'), ('final', 'Final')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
