# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0015_auto_20170909_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='source',
            new_name='wikipage',
        ),
        migrations.AddField(
            model_name='city',
            name='wikipage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stadium',
            name='wikipage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
