# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0018_auto_20170910_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='birth_date',
            new_name='foundation',
        ),
    ]
