# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0020_remove_tournament_champion_of_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonteamfinalstatus',
            name='goals_difference',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='seasonteamfinalstatus',
            name='status',
        ),
        migrations.AddField(
            model_name='seasonteamfinalstatus',
            name='status',
            field=models.ManyToManyField(blank=True, to='defense.TournamentStatus'),
        ),
    ]
