# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0021_auto_20170913_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
        migrations.AddField(
            model_name='coach',
            name='wikipage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='wikipage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='defense.Country'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='defense.Country'),
        ),
    ]
