# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0022_auto_20170915_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='type',
            field=models.CharField(choices=[('penalty', 'Penalty'), ('freekick', 'Freekick'), ('head', 'Head'), ('right', 'Right'), ('left', 'Left')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='playerteam',
            name='data_joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
