# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0023_auto_20170915_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentteam',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
