# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-17 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0024_tournamentteam_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
